import { createContext, useContext, useState } from 'react';

export const LANGS = [
  { code: 'en', label: 'English', flag: '🇬🇧', native: 'English' },
  { code: 'mr', label: 'Marathi', flag: '🇮🇳', native: 'मराठी' },
  { code: 'hi', label: 'Hindi',   flag: '🇮🇳', native: 'हिन्दी' },
];

const T = {
  en: {
    // Nav & Common
    appName: 'GrammConnect',
    appTagline: 'Smart Digital Gram Panchayat Portal',
    digitalIndia: 'Digital India',
    registerFamily: 'Register Family',
    backToLogin: '← Back to Login',
    logout: 'Logout',
    loading: 'Loading…',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    yes: 'Yes',
    no: 'No',
    search: 'Search…',
    status: 'Status',
    date: 'Date',
    actions: 'Actions',
    noData: 'No data found',
    selectLanguage: 'Language',

    // Login Page
    loginTitle: 'Your Village, Digitally Empowered',
    loginSub: 'Access government schemes, manage family records, pay taxes, and connect with your Gram Panchayat — all from one secure portal.',
    villages: 'Villages',
    families: 'Families',
    uptime: 'Uptime',
    selectLoginType: 'Select Login Type',
    selectLoginTypeSub: 'Choose your role to access the GrammConnect portal',
    adminLogin: 'Admin Login',
    adminDesc: 'Panchayat Administrator',
    headLogin: 'Head of Family',
    headDesc: 'Primary family account holder',
    memberLogin: 'Family Member',
    memberDesc: 'Member access to services',
    mobileEmail: 'Mobile / Email',
    mobileEmailPlaceholder: 'Mobile or email address',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    village: 'Village',
    villagePlaceholder: 'Village name',
    pincode: 'Pincode',
    forgotPassword: 'Forgot Password?',
    loginBtn: '🔑 Login to Portal',
    loggingIn: 'Logging in…',
    newHere: 'New here?',
    noAccount: "Don't have an account?",
    registerNow: 'Register Your Family',
    sslNote: '🔒 256-bit SSL · Aadhaar Safe · OTP Verified · Govt. of India',

    // Forgot Password
    resetPassword: 'Reset Password',
    forgotDesc: "Enter your registered mobile number. We'll send a one-time password.",
    mobileNumber: 'Mobile Number',
    mobilePlaceholder: '10-digit mobile',
    sendOtp: 'Send OTP',
    sending: 'Sending…',
    enter6Otp: 'Enter 6-Digit OTP',
    newPassword: 'New Password',
    minChars: 'Minimum 6 characters',
    verifyReset: 'Verify & Reset Password',

    // Signup
    familyRegistration: '👨‍👩‍👧‍👦 Family Registration',
    headRegTitle: 'Head of Family Registration',
    headRegSub: "Register as Head of Family to create your family's digital government account",
    headInfoStep: 'Head Info',
    membersStep: 'Members',
    securityStep: 'Security',
    headDetails: 'Head of Family Details',
    primaryHolder: 'Primary account holder information',
    fullName: 'Full Name',
    asPerAadhaar: 'As per Aadhaar',
    aadhaarNumber: 'Aadhaar Number',
    age: 'Age',
    gender: 'Gender',
    mobile: 'Mobile',
    address: 'Address',
    houseStreet: 'House No., Street',
    identityProof: 'Identity Proof',
    mandatory: 'Mandatory',
    aadhaar: 'Aadhaar',
    ration: 'Ration',
    voterId: 'Voter ID',
    clickUpload: 'Click to upload your document',
    uploadFormats: 'JPG, PNG or PDF · max 5MB',
    clickChange: 'Click to change',
    continueMembers: 'Continue → Add Members',
    familyMembers: 'Family Members',
    addHousehold: 'Add household members (optional)',
    primaryAccountHolder: 'Primary Account Holder',
    addMember: '＋ Add Family Member',
    newMember: '+ New Member',
    aadhaarLast4: 'Aadhaar Last 4',
    relation: 'Relation',
    saveMember: 'Save Member ✓',
    headAccessControls: '🛡 Head Access Controls',
    allowViewRecords: 'Allow members to view records',
    requireApproval: 'Require head approval for requests',
    freezeAccess: 'Freeze all member access',
    continueSecure: 'Continue → Security',
    familySecurity: 'Family Security',
    setPinSub: 'Set PIN, security question & verify mobile',
    pinInfoBox: 'ℹ️ Family members use this 4-digit PIN with their Aadhaar last 4 to login.',
    setFamilyPin: 'Set 4-Digit Family PIN',
    securityQuestion: 'Security Question',
    chooseQuestion: 'Choose a security question',
    yourAnswer: 'Your Answer',
    answerPlaceholder: 'Your answer (case-sensitive)',
    createPassword: 'Create Password',
    mobileOtpVerify: '📲 Mobile OTP Verification',
    sendOtpTo: 'Send OTP to +91 ',
    mobileVerified: '✅ Mobile Verified!',
    verifyOtp: 'Verify OTP',
    resend: 'Resend',
    registering: 'Registering…',
    registerFamily: 'Register Family ✓',
    familyRegistered: 'Family Registered!',
    registeredMsg: 'Your account is active. Login with your mobile number and password.',
    goLogin: 'Go to Login →',

    // Admin Dashboard
    dashboard: 'Dashboard',
    users: 'Users',
    certificates: 'Certificates',
    complaints: 'Complaints',
    taxManagement: 'Tax Management',
    sosAlerts: 'SOS Alerts',
    notifications: 'Notifications',
    documents: 'Documents',
    votingPolls: 'Voting Polls',
    assets: 'Assets',
    faceRegister: 'Face Register',
    adminPortal: 'Admin Portal',
    welcomeAdmin: 'Welcome back',
    totalFamilies: 'Total Families',
    pendingCerts: 'Pending Certs',
    openComplaints: 'Open Complaints',
    taxCollected: 'Tax Collected',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    assignTax: 'Assign Tax',
    sendNotification: 'Send Notification',
    createPoll: 'Create Poll',
    addAsset: 'Add Asset',
    approve: 'Approve',
    reject: 'Reject',
    resolve: 'Resolve',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    resolved: 'Resolved',
    active: 'Active',
    inactive: 'Inactive',
    activate: 'Activate',
    deactivate: 'Deactivate',

    // Villager Dashboard
    overview: 'Overview',
    payments: 'Payments',
    schemes: 'Schemes',
    gramSabha: 'Gram Sabha',
    sos: 'SOS',
    family: 'Family',
    voting: 'Voting',
    schemeChecker: 'Scheme Checker',
    voiceHelp: 'Voice Help',
    settings: 'Settings',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    welcomeMsg: 'Here\'s your village services overview',
    myCertificates: 'My Certificates',
    myComplaints: 'My Complaints',
    myPayments: 'My Payments',
    requestCert: 'Request Certificate',
    fileComplaint: 'File Complaint',
    payTax: 'Pay Tax',
    attendSabha: 'Attend Sabha',
    sendSOS: 'Send SOS',
    viewSchemes: 'View Schemes',
    livePhoto: '📸 Live Photo',
    captureWithGPS: 'Capture with GPS',
    photoLocation: 'Photo & Location',
    captureLive: 'Capture Live Photo',
    livePhotoDesc: 'Take a live photo with your GPS location for official records',
    openCamera: 'Open Camera',
    captured: 'Photo Captured!',
    locationTagged: 'Location tagged successfully',
    retake: 'Retake',
    savePhoto: 'Save & Submit',
    gettingLocation: 'Getting your location…',
    locationGranted: 'Location access granted',
    locationDenied: 'Location access denied',
    capturePhoto: 'Capture Photo',
    switchCamera: 'Switch Camera',
    profileSettings: 'Profile Settings',
    updateProfile: 'Update Profile',
    changePassword: 'Change Password',
    familyPin: 'Family PIN',
  },

  mr: {
    appName: 'ग्रामकनेक्ट',
    appTagline: 'स्मार्ट डिजिटल ग्राम पंचायत पोर्टल',
    digitalIndia: 'डिजिटल इंडिया',
    registerFamily: 'कुटुंब नोंदणी',
    backToLogin: '← लॉगिनकडे परत',
    logout: 'बाहेर पडा',
    loading: 'लोड होत आहे…',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    submit: 'सादर करा',
    close: 'बंद करा',
    back: 'मागे',
    next: 'पुढे',
    yes: 'होय',
    no: 'नाही',
    search: 'शोधा…',
    status: 'स्थिती',
    date: 'तारीख',
    actions: 'कृती',
    noData: 'माहिती आढळली नाही',
    selectLanguage: 'भाषा',
    loginTitle: 'तुमचे गाव, डिजिटली सशक्त',
    loginSub: 'सरकारी योजना, कौटुंबिक नोंदी, कर भरणा आणि ग्राम पंचायत — सर्व एकाच सुरक्षित पोर्टलवर.',
    villages: 'गावे',
    families: 'कुटुंबे',
    uptime: 'अपटाइम',
    selectLoginType: 'लॉगिन प्रकार निवडा',
    selectLoginTypeSub: 'ग्रामकनेक्ट पोर्टलमध्ये प्रवेशासाठी भूमिका निवडा',
    adminLogin: 'प्रशासक लॉगिन',
    adminDesc: 'पंचायत प्रशासक',
    headLogin: 'कुटुंब प्रमुख',
    headDesc: 'प्राथमिक कुटुंब खातेधारक',
    memberLogin: 'कुटुंब सदस्य',
    memberDesc: 'सेवांसाठी सदस्य प्रवेश',
    mobileEmail: 'मोबाइल / ईमेल',
    mobileEmailPlaceholder: 'मोबाइल किंवा ईमेल पत्ता',
    password: 'पासवर्ड',
    passwordPlaceholder: 'तुमचा पासवर्ड टाका',
    village: 'गाव',
    villagePlaceholder: 'गावाचे नाव',
    pincode: 'पिनकोड',
    forgotPassword: 'पासवर्ड विसरलात?',
    loginBtn: '🔑 पोर्टलमध्ये लॉगिन',
    loggingIn: 'लॉगिन होत आहे…',
    newHere: 'नवीन आहात?',
    noAccount: 'खाते नाही?',
    registerNow: 'कुटुंब नोंदणी करा',
    sslNote: '🔒 256-bit SSL · आधार सुरक्षित · OTP सत्यापित · भारत सरकार',
    resetPassword: 'पासवर्ड रीसेट',
    forgotDesc: 'तुमचा नोंदणीकृत मोबाइल नंबर टाका. आम्ही एक-वेळ पासवर्ड पाठवू.',
    mobileNumber: 'मोबाइल नंबर',
    mobilePlaceholder: '10-अंकी मोबाइल',
    sendOtp: 'OTP पाठवा',
    sending: 'पाठवत आहे…',
    enter6Otp: '6-अंकी OTP टाका',
    newPassword: 'नवीन पासवर्ड',
    minChars: 'किमान 6 अक्षरे',
    verifyReset: 'सत्यापित करा आणि पासवर्ड रीसेट करा',
    familyRegistration: '👨‍👩‍👧‍👦 कुटुंब नोंदणी',
    headRegTitle: 'कुटुंब प्रमुख नोंदणी',
    headRegSub: 'कुटुंबाचे डिजिटल सरकारी खाते तयार करण्यासाठी कुटुंब प्रमुख म्हणून नोंदणी करा',
    headInfoStep: 'प्रमुख माहिती',
    membersStep: 'सदस्य',
    securityStep: 'सुरक्षा',
    headDetails: 'कुटुंब प्रमुखाची माहिती',
    primaryHolder: 'प्राथमिक खातेधारक माहिती',
    fullName: 'पूर्ण नाव',
    asPerAadhaar: 'आधार प्रमाणे',
    aadhaarNumber: 'आधार क्रमांक',
    age: 'वय',
    gender: 'लिंग',
    mobile: 'मोबाइल',
    address: 'पत्ता',
    houseStreet: 'घर क्र., रस्ता',
    identityProof: 'ओळखपत्र',
    mandatory: 'अनिवार्य',
    aadhaar: 'आधार',
    ration: 'रेशन',
    voterId: 'मतदार ओळखपत्र',
    clickUpload: 'कागदपत्र अपलोड करण्यासाठी क्लिक करा',
    uploadFormats: 'JPG, PNG किंवा PDF · कमाल 5MB',
    clickChange: 'बदलण्यासाठी क्लिक करा',
    continueMembers: 'पुढे → सदस्य जोडा',
    familyMembers: 'कुटुंब सदस्य',
    addHousehold: 'घरातील सदस्य जोडा (ऐच्छिक)',
    primaryAccountHolder: 'प्राथमिक खातेधारक',
    addMember: '＋ कुटुंब सदस्य जोडा',
    newMember: '+ नवीन सदस्य',
    aadhaarLast4: 'आधार शेवटचे 4',
    relation: 'नाते',
    saveMember: 'सदस्य जतन करा ✓',
    headAccessControls: '🛡 प्रमुख प्रवेश नियंत्रण',
    allowViewRecords: 'सदस्यांना नोंदी पाहण्याची परवानगी',
    requireApproval: 'विनंत्यांसाठी प्रमुखाची मंजुरी आवश्यक',
    freezeAccess: 'सर्व सदस्यांचा प्रवेश थांबवा',
    continueSecure: 'पुढे → सुरक्षा',
    familySecurity: 'कुटुंब सुरक्षा',
    setPinSub: 'PIN, सुरक्षा प्रश्न आणि मोबाइल सत्यापित करा',
    pinInfoBox: 'ℹ️ कुटुंब सदस्य लॉगिनसाठी हे 4-अंकी PIN आणि त्यांचे आधार शेवटचे 4 वापरतात.',
    setFamilyPin: '4-अंकी कौटुंबिक PIN सेट करा',
    securityQuestion: 'सुरक्षा प्रश्न',
    chooseQuestion: 'सुरक्षा प्रश्न निवडा',
    yourAnswer: 'तुमचे उत्तर',
    answerPlaceholder: 'तुमचे उत्तर (केस-संवेदनशील)',
    createPassword: 'पासवर्ड तयार करा',
    mobileOtpVerify: '📲 मोबाइल OTP सत्यापन',
    sendOtpTo: 'OTP पाठवा +91 ',
    mobileVerified: '✅ मोबाइल सत्यापित!',
    verifyOtp: 'OTP सत्यापित करा',
    resend: 'पुन्हा पाठवा',
    registering: 'नोंदणी होत आहे…',
    registerFamily: 'कुटुंब नोंदणी ✓',
    familyRegistered: 'कुटुंब नोंदणी झाली!',
    registeredMsg: 'तुमचे खाते सक्रिय आहे. मोबाइल नंबर आणि पासवर्डने लॉगिन करा.',
    goLogin: 'लॉगिनकडे जा →',
    dashboard: 'डॅशबोर्ड',
    users: 'वापरकर्ते',
    certificates: 'प्रमाणपत्रे',
    complaints: 'तक्रारी',
    taxManagement: 'कर व्यवस्थापन',
    sosAlerts: 'SOS अलर्ट',
    notifications: 'सूचना',
    documents: 'कागदपत्रे',
    votingPolls: 'मतदान',
    assets: 'मालमत्ता',
    faceRegister: 'चेहरा नोंदणी',
    adminPortal: 'प्रशासक पोर्टल',
    welcomeAdmin: 'पुन्हा स्वागत',
    totalFamilies: 'एकूण कुटुंबे',
    pendingCerts: 'प्रलंबित प्रमाणपत्रे',
    openComplaints: 'खुल्या तक्रारी',
    taxCollected: 'कर संग्रह',
    recentActivity: 'अलीकडील क्रियाकलाप',
    quickActions: 'त्वरित क्रिया',
    assignTax: 'कर नियुक्त करा',
    sendNotification: 'सूचना पाठवा',
    createPoll: 'मतदान तयार करा',
    addAsset: 'मालमत्ता जोडा',
    approve: 'मंजूर करा',
    reject: 'नाकारा',
    resolve: 'निराकरण करा',
    pending: 'प्रलंबित',
    approved: 'मंजूर',
    rejected: 'नाकारलेले',
    resolved: 'निराकरण झाले',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    activate: 'सक्रिय करा',
    deactivate: 'निष्क्रिय करा',
    overview: 'आढावा',
    payments: 'देयके',
    schemes: 'योजना',
    gramSabha: 'ग्रामसभा',
    sos: 'SOS',
    family: 'कुटुंब',
    voting: 'मतदान',
    schemeChecker: 'योजना तपासक',
    voiceHelp: 'आवाज सहाय्य',
    settings: 'सेटिंग्ज',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    welcomeMsg: 'तुमचे ग्राम सेवा आढावा येथे आहे',
    myCertificates: 'माझी प्रमाणपत्रे',
    myComplaints: 'माझ्या तक्रारी',
    myPayments: 'माझी देयके',
    requestCert: 'प्रमाणपत्र विनंती',
    fileComplaint: 'तक्रार दाखल करा',
    payTax: 'कर भरा',
    attendSabha: 'सभेला उपस्थित',
    sendSOS: 'SOS पाठवा',
    viewSchemes: 'योजना पहा',
    livePhoto: '📸 थेट फोटो',
    captureWithGPS: 'GPS सह कॅप्चर',
    photoLocation: 'फोटो आणि स्थान',
    captureLive: 'थेट फोटो काढा',
    livePhotoDesc: 'अधिकृत नोंदींसाठी GPS स्थानासह थेट फोटो काढा',
    openCamera: 'कॅमेरा उघडा',
    captured: 'फोटो काढला!',
    locationTagged: 'स्थान यशस्वीरित्या टॅग केले',
    retake: 'पुन्हा काढा',
    savePhoto: 'जतन करा आणि सादर करा',
    gettingLocation: 'तुमचे स्थान मिळवत आहे…',
    locationGranted: 'स्थान प्रवेश मंजूर',
    locationDenied: 'स्थान प्रवेश नाकारला',
    capturePhoto: 'फोटो काढा',
    switchCamera: 'कॅमेरा बदला',
    profileSettings: 'प्रोफाइल सेटिंग्ज',
    updateProfile: 'प्रोफाइल अपडेट करा',
    changePassword: 'पासवर्ड बदला',
    familyPin: 'कौटुंबिक PIN',
  },

  hi: {
    appName: 'ग्रामकनेक्ट',
    appTagline: 'स्मार्ट डिजिटल ग्राम पंचायत पोर्टल',
    digitalIndia: 'डिजिटल इंडिया',
    registerFamily: 'परिवार पंजीकरण',
    backToLogin: '← लॉगिन पर वापस',
    logout: 'लॉगआउट',
    loading: 'लोड हो रहा है…',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    submit: 'जमा करें',
    close: 'बंद करें',
    back: 'वापस',
    next: 'अगला',
    yes: 'हाँ',
    no: 'नहीं',
    search: 'खोजें…',
    status: 'स्थिति',
    date: 'तारीख',
    actions: 'कार्रवाई',
    noData: 'कोई डेटा नहीं मिला',
    selectLanguage: 'भाषा',
    loginTitle: 'आपका गाँव, डिजिटल रूप से सशक्त',
    loginSub: 'सरकारी योजनाएं, पारिवारिक रिकॉर्ड, कर भुगतान और ग्राम पंचायत — सब एक सुरक्षित पोर्टल पर।',
    villages: 'गाँव',
    families: 'परिवार',
    uptime: 'अपटाइम',
    selectLoginType: 'लॉगिन प्रकार चुनें',
    selectLoginTypeSub: 'ग्रामकनेक्ट पोर्टल में प्रवेश के लिए अपनी भूमिका चुनें',
    adminLogin: 'प्रशासक लॉगिन',
    adminDesc: 'पंचायत प्रशासक',
    headLogin: 'परिवार का मुखिया',
    headDesc: 'प्राथमिक परिवार खाताधारक',
    memberLogin: 'परिवार का सदस्य',
    memberDesc: 'सेवाओं के लिए सदस्य पहुँच',
    mobileEmail: 'मोबाइल / ईमेल',
    mobileEmailPlaceholder: 'मोबाइल या ईमेल पता',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    village: 'गाँव',
    villagePlaceholder: 'गाँव का नाम',
    pincode: 'पिनकोड',
    forgotPassword: 'पासवर्ड भूल गए?',
    loginBtn: '🔑 पोर्टल में लॉगिन',
    loggingIn: 'लॉगिन हो रहा है…',
    newHere: 'नए हैं?',
    noAccount: 'खाता नहीं है?',
    registerNow: 'परिवार पंजीकरण करें',
    sslNote: '🔒 256-bit SSL · आधार सुरक्षित · OTP सत्यापित · भारत सरकार',
    resetPassword: 'पासवर्ड रीसेट',
    forgotDesc: 'अपना पंजीकृत मोबाइल नंबर दर्ज करें। हम एक-बार पासवर्ड भेजेंगे।',
    mobileNumber: 'मोबाइल नंबर',
    mobilePlaceholder: '10-अंकीय मोबाइल',
    sendOtp: 'OTP भेजें',
    sending: 'भेज रहे हैं…',
    enter6Otp: '6-अंकीय OTP दर्ज करें',
    newPassword: 'नया पासवर्ड',
    minChars: 'न्यूनतम 6 अक्षर',
    verifyReset: 'सत्यापित करें और पासवर्ड रीसेट करें',
    familyRegistration: '👨‍👩‍👧‍👦 परिवार पंजीकरण',
    headRegTitle: 'परिवार के मुखिया का पंजीकरण',
    headRegSub: 'अपने परिवार का डिजिटल सरकारी खाता बनाने के लिए मुखिया के रूप में पंजीकरण करें',
    headInfoStep: 'मुखिया जानकारी',
    membersStep: 'सदस्य',
    securityStep: 'सुरक्षा',
    headDetails: 'परिवार के मुखिया का विवरण',
    primaryHolder: 'प्राथमिक खाताधारक जानकारी',
    fullName: 'पूरा नाम',
    asPerAadhaar: 'आधार के अनुसार',
    aadhaarNumber: 'आधार नंबर',
    age: 'आयु',
    gender: 'लिंग',
    mobile: 'मोबाइल',
    address: 'पता',
    houseStreet: 'मकान नं., सड़क',
    identityProof: 'पहचान प्रमाण',
    mandatory: 'अनिवार्य',
    aadhaar: 'आधार',
    ration: 'राशन',
    voterId: 'मतदाता पहचान',
    clickUpload: 'दस्तावेज़ अपलोड करने के लिए क्लिक करें',
    uploadFormats: 'JPG, PNG या PDF · अधिकतम 5MB',
    clickChange: 'बदलने के लिए क्लिक करें',
    continueMembers: 'जारी रखें → सदस्य जोड़ें',
    familyMembers: 'परिवार के सदस्य',
    addHousehold: 'घर के सदस्य जोड़ें (वैकल्पिक)',
    primaryAccountHolder: 'प्राथमिक खाताधारक',
    addMember: '＋ परिवार का सदस्य जोड़ें',
    newMember: '+ नया सदस्य',
    aadhaarLast4: 'आधार अंतिम 4',
    relation: 'संबंध',
    saveMember: 'सदस्य सहेजें ✓',
    headAccessControls: '🛡 मुखिया पहुँच नियंत्रण',
    allowViewRecords: 'सदस्यों को रिकॉर्ड देखने की अनुमति',
    requireApproval: 'अनुरोधों के लिए मुखिया की स्वीकृति आवश्यक',
    freezeAccess: 'सभी सदस्यों की पहुँच रोकें',
    continueSecure: 'जारी रखें → सुरक्षा',
    familySecurity: 'परिवार सुरक्षा',
    setPinSub: 'PIN, सुरक्षा प्रश्न और मोबाइल सत्यापित करें',
    pinInfoBox: 'ℹ️ परिवार के सदस्य इस 4-अंकीय PIN और आधार के अंतिम 4 से लॉगिन करते हैं।',
    setFamilyPin: '4-अंकीय पारिवारिक PIN सेट करें',
    securityQuestion: 'सुरक्षा प्रश्न',
    chooseQuestion: 'सुरक्षा प्रश्न चुनें',
    yourAnswer: 'आपका उत्तर',
    answerPlaceholder: 'आपका उत्तर (केस-संवेदनशील)',
    createPassword: 'पासवर्ड बनाएं',
    mobileOtpVerify: '📲 मोबाइल OTP सत्यापन',
    sendOtpTo: 'OTP भेजें +91 ',
    mobileVerified: '✅ मोबाइल सत्यापित!',
    verifyOtp: 'OTP सत्यापित करें',
    resend: 'पुनः भेजें',
    registering: 'पंजीकरण हो रहा है…',
    registerFamily: 'परिवार पंजीकरण ✓',
    familyRegistered: 'परिवार पंजीकृत!',
    registeredMsg: 'आपका खाता सक्रिय है। मोबाइल नंबर और पासवर्ड से लॉगिन करें।',
    goLogin: 'लॉगिन पर जाएं →',
    dashboard: 'डैशबोर्ड',
    users: 'उपयोगकर्ता',
    certificates: 'प्रमाण पत्र',
    complaints: 'शिकायतें',
    taxManagement: 'कर प्रबंधन',
    sosAlerts: 'SOS अलर्ट',
    notifications: 'सूचनाएं',
    documents: 'दस्तावेज़',
    votingPolls: 'मतदान',
    assets: 'संपत्ति',
    faceRegister: 'चेहरा पंजीकरण',
    adminPortal: 'प्रशासक पोर्टल',
    welcomeAdmin: 'वापसी पर स्वागत',
    totalFamilies: 'कुल परिवार',
    pendingCerts: 'लंबित प्रमाण पत्र',
    openComplaints: 'खुली शिकायतें',
    taxCollected: 'कर संग्रह',
    recentActivity: 'हाल की गतिविधि',
    quickActions: 'त्वरित क्रियाएं',
    assignTax: 'कर नियुक्त करें',
    sendNotification: 'सूचना भेजें',
    createPoll: 'मतदान बनाएं',
    addAsset: 'संपत्ति जोड़ें',
    approve: 'स्वीकृत करें',
    reject: 'अस्वीकार करें',
    resolve: 'समाधान करें',
    pending: 'लंबित',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    resolved: 'समाधान हो गया',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    activate: 'सक्रिय करें',
    deactivate: 'निष्क्रिय करें',
    overview: 'अवलोकन',
    payments: 'भुगतान',
    schemes: 'योजनाएं',
    gramSabha: 'ग्राम सभा',
    sos: 'SOS',
    family: 'परिवार',
    voting: 'मतदान',
    schemeChecker: 'योजना जाँचकर्ता',
    voiceHelp: 'आवाज़ सहायता',
    settings: 'सेटिंग',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    welcomeMsg: 'यहाँ आपकी ग्राम सेवाओं का अवलोकन है',
    myCertificates: 'मेरे प्रमाण पत्र',
    myComplaints: 'मेरी शिकायतें',
    myPayments: 'मेरे भुगतान',
    requestCert: 'प्रमाण पत्र अनुरोध',
    fileComplaint: 'शिकायत दर्ज करें',
    payTax: 'कर भुगतान',
    attendSabha: 'सभा में उपस्थित हों',
    sendSOS: 'SOS भेजें',
    viewSchemes: 'योजनाएं देखें',
    livePhoto: '📸 लाइव फ़ोटो',
    captureWithGPS: 'GPS के साथ कैप्चर',
    photoLocation: 'फ़ोटो और स्थान',
    captureLive: 'लाइव फ़ोटो लें',
    livePhotoDesc: 'आधिकारिक रिकॉर्ड के लिए GPS स्थान के साथ लाइव फ़ोटो लें',
    openCamera: 'कैमरा खोलें',
    captured: 'फ़ोटो लिया गया!',
    locationTagged: 'स्थान सफलतापूर्वक टैग किया गया',
    retake: 'दोबारा लें',
    savePhoto: 'सहेजें और जमा करें',
    gettingLocation: 'आपका स्थान प्राप्त हो रहा है…',
    locationGranted: 'स्थान पहुँच स्वीकृत',
    locationDenied: 'स्थान पहुँच अस्वीकृत',
    capturePhoto: 'फ़ोटो लें',
    switchCamera: 'कैमरा बदलें',
    profileSettings: 'प्रोफ़ाइल सेटिंग',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    changePassword: 'पासवर्ड बदलें',
    familyPin: 'पारिवारिक PIN',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gc_lang') || 'en');

  const switchLang = (code) => {
    setLang(code);
    localStorage.setItem('gc_lang', code);
  };

  const t = (key) => T[lang]?.[key] || T.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, langs: LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
